# Form implementation generated from reading ui file 'GUI/designer/LibraryChooseDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LibraryChooseDialog(object):
    def setupUi(self, LibraryChooseDialog):
        LibraryChooseDialog.setObjectName("LibraryChooseDialog")
        LibraryChooseDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        LibraryChooseDialog.resize(532, 105)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LibraryChooseDialog.sizePolicy().hasHeightForWidth())
        LibraryChooseDialog.setSizePolicy(sizePolicy)
        LibraryChooseDialog.setMinimumSize(QtCore.QSize(0, 0))
        LibraryChooseDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(LibraryChooseDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windowLayout = QtWidgets.QVBoxLayout()
        self.windowLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.windowLayout.setContentsMargins(15, 15, 15, 15)
        self.windowLayout.setSpacing(10)
        self.windowLayout.setObjectName("windowLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectedPath = QtWidgets.QLineEdit(LibraryChooseDialog)
        self.selectedPath.setObjectName("selectedPath")
        self.horizontalLayout.addWidget(self.selectedPath)
        self.browse = QtWidgets.QPushButton(LibraryChooseDialog)
        self.browse.setObjectName("browse")
        self.horizontalLayout.addWidget(self.browse)
        self.windowLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(LibraryChooseDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply)
        self.buttonBox.setObjectName("buttonBox")
        self.windowLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.windowLayout)

        self.retranslateUi(LibraryChooseDialog)
        QtCore.QMetaObject.connectSlotsByName(LibraryChooseDialog)

    def retranslateUi(self, LibraryChooseDialog):
        _translate = QtCore.QCoreApplication.translate
        LibraryChooseDialog.setWindowTitle(_translate("LibraryChooseDialog", "Выберите галерею"))
        self.selectedPath.setPlaceholderText(_translate("LibraryChooseDialog", "Путь к папке..."))
        self.browse.setText(_translate("LibraryChooseDialog", "Выбрать"))
