# Form implementation generated from reading ui file 'GUI/designer/LibraryChooseDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LibraryChooseDialog(object):
    def setupUi(self, LibraryChooseDialog):
        LibraryChooseDialog.setObjectName("LibraryChooseDialog")
        LibraryChooseDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        LibraryChooseDialog.resize(532, 105)
        LibraryChooseDialog.setModal(True)
        self.LibraryChooseDialogLayout = QtWidgets.QVBoxLayout(LibraryChooseDialog)
        self.LibraryChooseDialogLayout.setContentsMargins(0, 0, 0, 0)
        self.LibraryChooseDialogLayout.setSpacing(0)
        self.LibraryChooseDialogLayout.setObjectName("LibraryChooseDialogLayout")
        self.ContainerWidget = QtWidgets.QWidget(LibraryChooseDialog)
        self.ContainerWidget.setObjectName("ContainerWidget")
        self.ContainerWidgetLayout = QtWidgets.QVBoxLayout(self.ContainerWidget)
        self.ContainerWidgetLayout.setContentsMargins(15, 15, 15, 15)
        self.ContainerWidgetLayout.setSpacing(10)
        self.ContainerWidgetLayout.setObjectName("ContainerWidgetLayout")
        self.SelectControlsWidget = QtWidgets.QWidget(self.ContainerWidget)
        self.SelectControlsWidget.setObjectName("SelectControlsWidget")
        self.SelectControlsWidgetLayout = QtWidgets.QHBoxLayout(self.SelectControlsWidget)
        self.SelectControlsWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.SelectControlsWidgetLayout.setObjectName("SelectControlsWidgetLayout")
        self.SelectedPathLineEdit = QtWidgets.QLineEdit(self.SelectControlsWidget)
        self.SelectedPathLineEdit.setObjectName("SelectedPathLineEdit")
        self.SelectControlsWidgetLayout.addWidget(self.SelectedPathLineEdit)
        self.BrowseButton = QtWidgets.QPushButton(self.SelectControlsWidget)
        self.BrowseButton.setObjectName("BrowseButton")
        self.SelectControlsWidgetLayout.addWidget(self.BrowseButton)
        self.ContainerWidgetLayout.addWidget(self.SelectControlsWidget)
        self.ApplyButton = QtWidgets.QPushButton(self.ContainerWidget)
        self.ApplyButton.setObjectName("ApplyButton")
        self.ContainerWidgetLayout.addWidget(self.ApplyButton)
        self.LibraryChooseDialogLayout.addWidget(self.ContainerWidget)

        self.retranslateUi(LibraryChooseDialog)
        QtCore.QMetaObject.connectSlotsByName(LibraryChooseDialog)

    def retranslateUi(self, LibraryChooseDialog):
        _translate = QtCore.QCoreApplication.translate
        LibraryChooseDialog.setWindowTitle(_translate("LibraryChooseDialog", "Choose a gallery folder"))
        self.SelectedPathLineEdit.setPlaceholderText(_translate("LibraryChooseDialog", "Gallery path"))
        self.BrowseButton.setText(_translate("LibraryChooseDialog", "Browse..."))
        self.ApplyButton.setText(_translate("LibraryChooseDialog", "Apply"))
