# Form implementation generated from reading ui file 'GUI/designer/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 440)
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.CentralContentWidget = QtWidgets.QWidget(MainWindow)
        self.CentralContentWidget.setObjectName("CentralContentWidget")
        self.CentralContentWidgetLayout = QtWidgets.QHBoxLayout(self.CentralContentWidget)
        self.CentralContentWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.CentralContentWidgetLayout.setSpacing(0)
        self.CentralContentWidgetLayout.setObjectName("CentralContentWidgetLayout")
        self.LeftColumnWidget = QtWidgets.QWidget(self.CentralContentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftColumnWidget.sizePolicy().hasHeightForWidth())
        self.LeftColumnWidget.setSizePolicy(sizePolicy)
        self.LeftColumnWidget.setObjectName("LeftColumnWidget")
        self.CentralContentWidgetLayout.addWidget(self.LeftColumnWidget)
        self.RightColumnWidget = QtWidgets.QWidget(self.CentralContentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightColumnWidget.sizePolicy().hasHeightForWidth())
        self.RightColumnWidget.setSizePolicy(sizePolicy)
        self.RightColumnWidget.setObjectName("RightColumnWidget")
        self.RightColumnWidgetLayout = QtWidgets.QVBoxLayout(self.RightColumnWidget)
        self.RightColumnWidgetLayout.setObjectName("RightColumnWidgetLayout")
        self.FilePreviewGraphicsView = QtWidgets.QGraphicsView(self.RightColumnWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FilePreviewGraphicsView.sizePolicy().hasHeightForWidth())
        self.FilePreviewGraphicsView.setSizePolicy(sizePolicy)
        self.FilePreviewGraphicsView.setObjectName("FilePreviewGraphicsView")
        self.RightColumnWidgetLayout.addWidget(self.FilePreviewGraphicsView)
        self.FileInfoGroupBox = QtWidgets.QGroupBox(self.RightColumnWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FileInfoGroupBox.sizePolicy().hasHeightForWidth())
        self.FileInfoGroupBox.setSizePolicy(sizePolicy)
        self.FileInfoGroupBox.setObjectName("FileInfoGroupBox")
        self.FileInfoGroupBoxLayout = QtWidgets.QFormLayout(self.FileInfoGroupBox)
        self.FileInfoGroupBoxLayout.setObjectName("FileInfoGroupBoxLayout")
        self.TitleFileNameLabel = QtWidgets.QLabel(self.FileInfoGroupBox)
        self.TitleFileNameLabel.setObjectName("TitleFileNameLabel")
        self.FileInfoGroupBoxLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.TitleFileNameLabel)
        self.FileNameLabel = QtWidgets.QLabel(self.FileInfoGroupBox)
        self.FileNameLabel.setText("")
        self.FileNameLabel.setObjectName("FileNameLabel")
        self.FileInfoGroupBoxLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.FileNameLabel)
        self.RightColumnWidgetLayout.addWidget(self.FileInfoGroupBox)
        self.CentralContentWidgetLayout.addWidget(self.RightColumnWidget)
        MainWindow.setCentralWidget(self.CentralContentWidget)
        self.MenuBar = QtWidgets.QMenuBar(MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 550, 21))
        self.MenuBar.setObjectName("MenuBar")
        self.FileMenu = QtWidgets.QMenu(self.MenuBar)
        self.FileMenu.setObjectName("FileMenu")
        MainWindow.setMenuBar(self.MenuBar)
        self.OpenAction = QtGui.QAction(MainWindow)
        self.OpenAction.setObjectName("OpenAction")
        self.FileMenu.addAction(self.OpenAction)
        self.MenuBar.addAction(self.FileMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hello world"))
        self.FileInfoGroupBox.setTitle(_translate("MainWindow", "Информация о файле"))
        self.TitleFileNameLabel.setText(_translate("MainWindow", "Имя файла:"))
        self.FileMenu.setTitle(_translate("MainWindow", " Файл"))
        self.OpenAction.setText(_translate("MainWindow", "Открыть"))
