# Form implementation generated from reading ui file 'gui\ui\LibraryChoose.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LibraryChoose(object):
    def setupUi(self, LibraryChoose):
        LibraryChoose.setObjectName("LibraryChoose")
        LibraryChoose.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        LibraryChoose.resize(400, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LibraryChoose.sizePolicy().hasHeightForWidth())
        LibraryChoose.setSizePolicy(sizePolicy)
        LibraryChoose.setMinimumSize(QtCore.QSize(400, 120))
        LibraryChoose.setMaximumSize(QtCore.QSize(400, 120))
        self.verticalLayout = QtWidgets.QVBoxLayout(LibraryChoose)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(-1, 10, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.chooseButton = QtWidgets.QPushButton(LibraryChoose)
        self.chooseButton.setObjectName("chooseButton")
        self.gridLayout.addWidget(self.chooseButton, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(LibraryChoose)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(LibraryChoose)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(LibraryChoose)
        QtCore.QMetaObject.connectSlotsByName(LibraryChoose)

    def retranslateUi(self, LibraryChoose):
        _translate = QtCore.QCoreApplication.translate
        LibraryChoose.setWindowTitle(_translate("LibraryChoose", "Выбор библиотеки"))
        self.chooseButton.setText(_translate("LibraryChoose", "Выбрать"))
        self.lineEdit.setPlaceholderText(_translate("LibraryChoose", "Выберите путь к библиотеке"))
        self.okButton.setText(_translate("LibraryChoose", "Ок"))
